language: node_js
node_js:
 - "12.14"
branches:
  only:
    - master
addons:
  chrome: stable
before_script:
   - npm install -g @angular/cli
cache:
  npm: true
  directories:
    - node_modules   
script:  
   - ng test --watch=false
   - ng build --prod 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true  
  on:            