language: node_js
node_js:
 - "12.14"
dist: trusty 
branches:
  only:
    - master
addons:
  chrome: stable
before_script:
   - npm install -g @angular/cli
cache:
  npm: true
  directories:
    - node_modules   
script:  
    - ng build --prod --base-href https://feb-git-2021.github.io/my-repo/full-stack-app-ng 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/my-repo
  keep-history: true  
  on:
    branch: master            